new src

diff --git a/src/platform2/login_manager/init/scripts/ui-pre-start b/src/platform2/login_manager/init/scripts/ui-pre-start
--- a/src/platform2/login_manager/init/scripts/ui-pre-start
+++ b/src/platform2/login_manager/init/scripts/ui-pre-start
@@ -1,12 +1,31 @@
 #!/bin/sh
 
-# Copyright 2016 The Chromium OS Authors. All rights reserved.
+# Copyright 2016 The ChromiumOS Authors
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
 set -e
 
 JOB=$(basename "$0")
+
+DEVICE_SHUTTING_DOWN=4 # Defined in session_manager_service.h
+
+# Check if file exists and is writeable by us. -w is always true under root.
+is_writeable() {
+  local file="$1"
+  local v=0
+
+  if [ -f "${file}" ]; then
+    local wfile
+    wfile=$(find "${file}" -maxdepth 1 | awk '$1 ~ /^.*w.*/ { print $NF; }')
+
+    if [ -n "${wfile}" ]; then
+      v=1
+    fi
+  fi
+
+  echo "${v}"
+}
 
 # Read chrome OS configurations
 read_cros_config() {
@@ -19,8 +38,8 @@ read_cros_config() {
 }
 
 read_cros_config_int() {
-  local v=$(read_cros_config "$@")
-
+  local v
+  v=$(read_cros_config "$@")
   # config value should be an integer
   case "${v}" in
     ''|*[!0-9]*)
@@ -34,6 +53,17 @@ read_cros_config_int() {
       ;;
     esac
 }
+
+# The ui job can be restarted asynchronously via ui-respawn. This allows the
+# possibility that ui can be started while shutdown/reboot is in process.
+# Make sure that the reboot/halt jobs are not active at the time we are
+# restarting ui.
+if ! initctl status reboot | grep -q 'stop/waiting' || \
+    ! initctl status halt | grep -q 'stop/waiting'; then
+  logger -t "${UPSTART_JOB:-}" "ERROR: reboot/shutdown in progress, quit."
+  stop ui
+  exit "${DEVICE_SHUTTING_DOWN}"
+fi
 
 # Setup drm log tracing if available. This will allow us to access more verbose
 # logs to debug display connectivity issues when they arise. The traces are
@@ -54,23 +84,29 @@ if [ -w "${DRM_TRACE_MASK}" ]; then
   # 0x106 corresponds to (DRM_UT_DRIVER | DRM_UT_KMS | DRM_UT_DP).
   echo 0x106 > "${DRM_TRACE_MASK}"
 fi
-DRM_TRACEFS_INSTANCE="/sys/kernel/debug/tracing/instances/drm"
+DRM_TRACEFS_INSTANCE="/sys/kernel/tracing/instances/drm"
 DRM_TRACEFS_BUF_SIZE="${DRM_TRACEFS_INSTANCE}/buffer_size_kb"
 if [ -w "${DRM_TRACEFS_BUF_SIZE}" ]; then
   # 64kB per-cpu of drm logs.
   echo 64 > "${DRM_TRACEFS_BUF_SIZE}"
 fi
 
-mkdir -p "${UI_LOG_DIR}"
-ln -sf ui.$(date +%Y%m%d-%H%M%S) "${UI_LOG_DIR}/${UI_LOG_FILE}"
+mkdir -p "${UI_LOG_DIR:-}"
+ln -sf ui."$(date --utc +%Y%m%d-%H%M%S)" "${UI_LOG_DIR}/${UI_LOG_FILE:-}"
 
-mkdir -p "${CONTAINER_ROOT_DIR}"
+mkdir -p "${CONTAINER_ROOT_DIR:-}"
+
+# Create support directory for Chrome to write its support files and give
+# ownership to Chronos since only interaction will be done by it.
+SUPPORT_DIR="/var/spool/support"
+mkdir -p "${SUPPORT_DIR}"
+chown -R chronos "${SUPPORT_DIR}"
 
 # Create a top-level cpu cgroup for ui tasks.  This will be used to share cpu
 # resources with tasks not managed by the UI.  Android will be placed in a
 # parallel cgroup allowing priority to be given to one or the other depending
 # on what the user is doing at the time.
-if [ ! -d "${UI_CPU_CGROUP_DIR}" ]; then
+if [ ! -d "${UI_CPU_CGROUP_DIR:-}" ]; then
   mkdir -p "${UI_CPU_CGROUP_DIR}"
 fi
 
@@ -84,28 +120,32 @@ if [ ! -d "${CHROME_CPU_CGROUP_DIR}" ]; then
   mkdir -p "${CHROME_CPU_CGROUP_DIR}/foreground"
   mkdir -p "${CHROME_CPU_CGROUP_DIR}/background"
   echo "10" > "${CHROME_CPU_CGROUP_DIR}/background/cpu.shares"
+  # Allow featured to still modify these values
+  chmod -R g+w "${CHROME_CPU_CGROUP_DIR}"
   chown -R chronos "${CHROME_CPU_CGROUP_DIR}"
-fi
 
-# TODO(ikjn): This scheduler settings are a bit complex,
-# Let's move these out to an another executable (c++).
-# Tracked in b/182958867
+  # TODO(ikjn): This scheduler settings are a bit complex,
+  # Let's move these out to an another executable (c++).
+  # Tracked in b/182958867
 
-# apply ui and chrome foreground cgroup's uclamp.min, default 20%,
-v=$(read_cros_config_int "/scheduler-tune" "boost-urgent" "20")
-for knob in "${UI_CPU_CGROUP_DIR}/cpu.uclamp.min" \
-            "${CHROME_CPU_CGROUP_DIR}/cpu.uclamp.min" \
-            "${CHROME_CPU_CGROUP_DIR}/foreground/cpu.uclamp.min"; do
-  if [ -f "${knob}" ]; then
-    echo "${v}" > "${knob}"
+  # We only do this once when we initially create the cgroups.
+  # Apply ui and chrome foreground cgroup's uclamp.min, default 20%,
+  v=$(read_cros_config_int "/scheduler-tune" "boost-urgent" "20")
+  for knob in "${UI_CPU_CGROUP_DIR}/cpu.uclamp.min" \
+              "${CHROME_CPU_CGROUP_DIR}/cpu.uclamp.min" \
+              "${CHROME_CPU_CGROUP_DIR}/foreground/cpu.uclamp.min"; do
+    if [ -f "${knob}" ]; then
+      echo "${v}" > "${knob}"
+    fi
+  done
+
+  # Apply boosting values for platforms using schedtune
+  # Will be removed soon (b/271420003)
+  SCHEDTUNE_BOOST_DIR=/sys/fs/cgroup/schedtune/chrome/urgent
+  if [ -d "${SCHEDTUNE_BOOST_DIR}" ]; then
+    echo "${v}" > "${SCHEDTUNE_BOOST_DIR}/schedtune.boost"
+    echo "1" > "${SCHEDTUNE_BOOST_DIR}/schedtune.prefer_idle"
   fi
-done
-
-# Apply boosting values for platforms using schedtune
-SCHEDTUNE_BOOST_DIR=/sys/fs/cgroup/schedtune/chrome/urgent
-if [ -d "${SCHEDTUNE_BOOST_DIR}" ]; then
-  echo "${v}" > "${SCHEDTUNE_BOOST_DIR}/schedtune.boost"
-  echo "1" > "${SCHEDTUNE_BOOST_DIR}/schedtune.prefer_idle"
 fi
 
 # Apply Input boosting
@@ -116,8 +156,9 @@ CPUFREQ_CONF=/etc/cpufreq.conf
 if [ -f "${INPUT_BOOST}" ]; then
   # Default value is 75 for platforms using EAS
   if [ -f "${CPUFREQ_CONF}" ]; then
+    # shellcheck source=/dev/null
     . "${CPUFREQ_CONF}"
-    if [ "${CPUFREQ_GOVERNOR}" = "schedutil" ] || \
+    if [ "${CPUFREQ_GOVERNOR:-}" = "schedutil" ] || \
        [ "${CPUFREQ_GOVERNOR}" = "sched" ]; then
       INPUT_BOOST_DEFAULT=75
     fi
@@ -126,66 +167,18 @@ if [ -f "${INPUT_BOOST}" ]; then
     "${INPUT_BOOST_DEFAULT}" > "${INPUT_BOOST}"
 fi
 
-# Limit non-urgent tasks to small cores
-CPUBUSDIR=/sys/bus/cpu/devices
-CPUSET_NONURGENT_DIR=/sys/fs/cgroup/cpuset/chrome/non-urgent
-if [ -d "${CPUSET_NONURGENT_DIR}" ]; then
-  v=$(read_cros_config "/scheduler-tune" "cpuset-nonurgent" "")
-
-  # If a cpuset-nonurgent isn't specified in cros_config,
-  # use all little cores as a non-urgent cpuset.
-  if [ -z "${v}" ] && grep -q '^big_little$' /etc/ui_use_flags.txt; then
-    nr_cpus=0
-    nr_small_cpus=0
-    min_cap=1025
-    cpus=""
-    prefix="${CPUBUSDIR}/cpu"
-    for cpu in ${CPUBUSDIR}/cpu*; do
-      if [ ! -f "${cpu}/cpu_capacity" ]; then
-        cpus=""
-        break;
-      fi
-      cap=$(cat "${cpu}/cpu_capacity")
-      if [ "${cap}" -lt "${min_cap}" ]; then
-        cpus="${cpu##${prefix}}"
-        min_cap="${cap}"
-        nr_small_cpus=1
-      elif [ "${cap}" -eq "${min_cap}" ]; then
-        cpus="${cpus},${cpu##${prefix}}"
-        nr_small_cpus=$((nr_small_cpus + 1))
-      fi
-      nr_cpus=$((nr_cpus + 1))
-    done
-    if [ "${nr_small_cpus}" -lt "${nr_cpus}" ]; then
-      v="${cpus}"
-    fi
-  fi
-
-  if [ -n "${v}" ]; then
-    echo "${v}" > "${CPUSET_NONURGENT_DIR}/cpus"
-  fi
-fi
-
-# Set up a folder on the stateful partition for ephemeral encrypted swap
-# files.
-USERSPACE_SWAP_DIR=/mnt/stateful_partition/unencrypted/userspace_swap.tmp/
-if [ ! -d "${USERSPACE_SWAP_DIR}" ]; then
-  mkdir -p "${USERSPACE_SWAP_DIR}"
-  chown -R chronos "${USERSPACE_SWAP_DIR}"
-fi
-
 # Set up the ui freezer cgroup. This is used during suspend to order the
 # freezing of processes to avoid FUSE causing freeze to timeout.
-if [ ! -d ${UI_FREEZER_CGROUP_DIR} ]; then
-  mkdir -p ${UI_FREEZER_CGROUP_DIR}
-  chown -R chronos ${UI_FREEZER_CGROUP_DIR}
-  chown power:power ${UI_FREEZER_CGROUP_DIR}/freezer.state
+if [ ! -d "${UI_FREEZER_CGROUP_DIR:-}" ]; then
+  mkdir -p "${UI_FREEZER_CGROUP_DIR}"
+  chown -R chronos "${UI_FREEZER_CGROUP_DIR}"
+  chown power:power "${UI_FREEZER_CGROUP_DIR}"/freezer.state
 fi
 
 # Set up the renderer freezer.  This is used during the suspend/resume cycle
 # to freeze all the chrome renderers so that they don't take up a lot of power
 # when the system comes up in dark resume
-if [ ! -d "${CHROME_FREEZER_CGROUP_DIR}" ]; then
+if [ ! -d "${CHROME_FREEZER_CGROUP_DIR:-}" ]; then
   mkdir -p "${CHROME_FREEZER_CGROUP_DIR}"
   mkdir -p "${CHROME_FREEZER_CGROUP_DIR}/to_be_frozen"
   chown -R chronos "${CHROME_FREEZER_CGROUP_DIR}"
@@ -207,6 +200,23 @@ fi
 # Enable madvise(MADV_HUGEPAGE) for VMs guest mappings
 if [ -f "/sys/kernel/mm/transparent_hugepage/shmem_enabled" ]; then
   echo "advise" > "/sys/kernel/mm/transparent_hugepage/shmem_enabled"
+fi
+
+# Tweak KVM HLT polling only for x86
+if uname -m | grep -q x86; then
+  HALT_POLL_NS_SHRINK=/sys/module/kvm/parameters/halt_poll_ns_shrink
+  HALT_POLL_NS=/sys/module/kvm/parameters/halt_poll_ns
+  # Older kernels (e.g. 4.4) do not permit dynamic halt_poll_ns_shrink and
+  # have this attr as read-only.
+  v=$(is_writeable "${HALT_POLL_NS_SHRINK}")
+  if [ "${v}" != "0" ]; then
+    echo 2 > "${HALT_POLL_NS_SHRINK}"
+  fi
+  # Ditto, just in case
+  v=$(is_writeable "${HALT_POLL_NS}")
+  if [ "${v}" != "0" ]; then
+    echo 160000 > "${HALT_POLL_NS}"
+  fi
 fi
 
 if crossystem "cros_debug?1"; then
diff --git a/src/scripts/update_chroot b/src/scripts/update_chroot
--- a/src/scripts/update_chroot
+++ b/src/scripts/update_chroot
@@ -1,10 +1,10 @@
 #!/bin/bash
 
-# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
+# Copyright 2012 The ChromiumOS Authors
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
-
+# shellcheck source=common.sh
 . "$(dirname "$0")/common.sh" || exit 1
 
 # Script must run inside the chroot
@@ -14,10 +14,10 @@ assert_inside_chroot "$@"
 assert_not_root_user
 
 # Developer-visible flags.
-DEFINE_boolean usepkg $FLAGS_TRUE \
+DEFINE_boolean usepkg "${FLAGS_TRUE}" \
   "Use binary packages to bootstrap."
 
-FLAGS_HELP="usage: $(basename $0) [flags]
+FLAGS_HELP="usage: $(basename "$0") [flags]
 Performs an update of the chroot. This script is called as part of
 build_packages, so there is typically no need to call this script directly.
 "
@@ -27,11 +27,12 @@ build_packages, so there is typically no need to call this script directly.
 # not needed for the typical developer workflow.
 DEFINE_integer jobs -1 \
   "How many packages to build in parallel at maximum."
-DEFINE_boolean skip_toolchain_update $FLAGS_FALSE \
+DEFINE_boolean skip_toolchain_update "${FLAGS_FALSE}" \
   "Don't update the toolchains."
 DEFINE_string toolchain_boards "" \
   "Extra toolchains to setup for the specified boards."
 DEFINE_boolean eclean "${FLAGS_TRUE}" "Run eclean to delete old binpkgs."
+DEFINE_integer backtrack 10 "See emerge --backtrack."
 
 # Parse command line flags
 FLAGS "$@" || exit 1
@@ -41,7 +42,8 @@ eval set -- "${FLAGS_ARGV}"
 # so will die prematurely if 'switch_to_strict_mode' is specified before now.
 switch_to_strict_mode
 
-. ${SCRIPTS_DIR}/sdk_lib/make_conf_util.sh
+# shellcheck source=sdk_lib/make_conf_util.sh
+. "${SCRIPTS_DIR}"/sdk_lib/make_conf_util.sh
 
 # Run version hooks as pre-update
 run_chroot_version_hooks
@@ -61,16 +63,14 @@ create_host_setup
 
 sudo_clear_shadow_locks /
 
-# First make sure the cross-compilers have the right config settings.
-# We don't actually build them yet though as we want to wait for the
-# sdk to have all up-to-date packages.
+# First update the cross-compilers.
+# Note that this uses binpkgs only, unless we pass --nousepkg below.
 if [ "${FLAGS_skip_toolchain_update}" -eq "${FLAGS_FALSE}" ]; then
   info "Updating cross-compilers"
   TOOLCHAIN_FLAGS=()
 
   if [[ -n ${FLAGS_toolchain_boards} ]]; then
     TOOLCHAIN_FLAGS+=(
-      "--targets=boards"
       "--include-boards=${FLAGS_toolchain_boards}"
     )
   fi
@@ -80,14 +80,25 @@ if [ "${FLAGS_skip_toolchain_update}" -eq "${FLAGS_FALSE}" ]; then
     TOOLCHAIN_FLAGS+=( --nousepkg )
   fi
   # Expand the path before sudo, as root doesn't have the same path magic.
-  info_run sudo -E $(type -p cros_setup_toolchains) "${TOOLCHAIN_FLAGS[@]}"
+  info_run sudo -E "$(type -p cros_setup_toolchains)" "${TOOLCHAIN_FLAGS[@]}"
 fi
 
 # Make sure depot_tools is bootstrapped, so that it can build chromeos-chrome.
 info "Bootstrapping depot_tools"
-ensure_bootstrap
+"${DEPOT_TOOLS_DIR}"/ensure_bootstrap
 
-# Perform an update of all the sdk packages in the chroot.
+# Clean outdated packages in SDK.
+CONFIG_DIR="${HOME}/.config"
+if [[ "${USER}" == "chrome-bot" ]]; then
+  CONFIG_DIR=$(python -c "import tempfile; print(tempfile.gettempdir())")
+  CONFIG_DIR+="/.config/"
+fi
+if [[ ! -e "${CONFIG_DIR}/chromite/autocop-off" ]] && \
+   [[ "${CROS_CLEAN_OUTDATED_PKGS}" != "0" ]]; then
+  # Use "|| true" to not exit on errors for one command.
+  cros clean-outdated-pkgs --host || true
+fi
+
 EMERGE_CMD="${CHROMITE_BIN}/parallel_emerge"
 
 info "Rebuilding Portage cache"
@@ -104,19 +115,18 @@ fi
 
 info "Updating the SDK"
 
-EMERGE_FLAGS=( -uNv --with-bdeps=y )
+EMERGE_FLAGS=( -uNv --with-bdeps=y --backtrack="${FLAGS_backtrack}" )
 if [ "${FLAGS_usepkg}" -eq "${FLAGS_TRUE}" ]; then
   EMERGE_FLAGS+=( --getbinpkg )
 
-  # Only update toolchain when binpkgs are available. Toolchain rollout
-  # process only takes place when the chromiumos sdk builder finishes
-  # a successful build.
+  # Avoid building toolchain packages or "post-cross" packages from
+  # source. The toolchain rollout process only takes place when the
+  # chromiumos-sdk builder finishes a successful build.
   PACKAGES=(
     $("${CHROMITE_BIN}/cros_setup_toolchains" --show-packages host)
   )
   # Sanity check we got some valid results.
   [[ ${#PACKAGES[@]} -eq 0 ]] && die_notrace "cros_setup_toolchains failed"
-  # Update post cross-packages. This is needed to update rust.
   PACKAGES+=(
     $("${CHROMITE_BIN}/cros_setup_toolchains" --show-packages host-post-cross)
   )
@@ -135,13 +145,22 @@ done
 
 # Second pass, update everything else.
 EMERGE_FLAGS+=( --deep )
-info_run sudo -E ${EMERGE_CMD} "${EMERGE_FLAGS[@]}" virtual/target-sdk world
+info_run sudo -E "${EMERGE_CMD}" "${EMERGE_FLAGS[@]}" virtual/target-sdk world
 
-# Install post cross packages if binary pkgs are available.
 if [ "${FLAGS_usepkg}" -eq "${FLAGS_TRUE}" ]; then
+  # Update "post-cross" packages.
+  # Use --usepkgonly to ensure that packages are not built from source.
+  EMERGE_FLAGS=( -uNv --with-bdeps=y --oneshot --getbinpkg --deep )
+  EMERGE_FLAGS+=( --usepkgonly --rebuilt-binaries=n )
+  EMERGE_FLAGS+=(
+    $("${CHROMITE_BIN}/cros_setup_toolchains" --show-packages host-post-cross)
+  )
+  sudo -E "${EMERGE_CMD}" "${EMERGE_FLAGS[@]}"
+
   # Install nobdeps packages only when binary pkgs are available, since we don't
   # want to accidentally pull in build deps for a rebuild.
-  EMERGE_FLAGS=( -uNv --with-bdeps=n --oneshot --getbinpkg --deep --usepkgonly )
+  EMERGE_FLAGS=( -uNv --with-bdeps=n --oneshot --getbinpkg --deep )
+  EMERGE_FLAGS+=( --usepkgonly --rebuilt-binaries=n )
   info_run sudo -E "${EMERGE_CMD}" "${EMERGE_FLAGS[@]}" \
     virtual/target-sdk-nobdeps
 fi
@@ -160,5 +179,9 @@ if [[ "${FLAGS_eclean}" -eq "${FLAGS_TRUE}" ]]; then
   info "Deep cleaning stale binpkgs"
   get_eclean_exclusions | sudo eclean -e /dev/stdin -d packages
 fi
+
+# Generate /usr/bin/remote_toolchain_inputs file for Reclient used by Chrome
+# for distributed builds, go/rbe/dev/x/reclient .
+info_run generate_reclient_inputs
 
 command_completed
